### ISSUE TITLE
Transform API should implement the sklearn api or provide an adapter 

### ISSUE THREAD

**Issue by mauricekraus** [mauricekraus/torchchronos#18]
Currently the transform API does not fully align with the sklearn api, which hinders the usage of sklearn transforms directly.

We should support: 
```
fit, transform, inverse_transform

```

We only support:
```
fit, __call__
```

Something like a wrapper would also be a feasible solution

**Comment by felixdivo** [comment]
Changing the API sounds sensible. We can still support `__call__`, which sometimes makes the syntax of using them a bit nicer.
